# Generated by Django 4.0.10 on 2023-07-27 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='заголовок')),
                ('description', models.TextField(verbose_name='описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='цена')),
                ('auction', models.BooleanField(help_text='Если торг уместен, то True(1), если не уместен - False(0)', verbose_name='торг')),
                ('created_data', models.DateTimeField(auto_now_add=True, verbose_name='дата публикации')),
                ('updated_data', models.DateTimeField(auto_now=True, verbose_name='дата обновления')),
            ],
        ),
    ]
