# Generated by Django 4.0.10 on 2023-08-02 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_advertisements', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='advertisement',
            table='advertisement',
        ),
    ]
